// Generated by `flutterfire configure --project=flutter-and-friends-ad8fe`
// for the conference's Firebase project (the same project the website
// deploys to). Re-run that command to add a platform or refresh the values.
//
// These are client identifiers, not secrets: access to data is governed by
// the Firestore security rules in `firestore.rules`.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static bool get isSupportedPlatform {
    if (kIsWeb) return true;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android || TargetPlatform.iOS => true,
      TargetPlatform.macOS ||
      TargetPlatform.windows ||
      TargetPlatform.linux ||
      TargetPlatform.fuchsia => false,
    };
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXPJ7cyClx6J6DD0JgxwQfzzTEQ9ZmGM4',
    appId: '1:148076616084:web:b227078a6c8069da38d781',
    messagingSenderId: '148076616084',
    projectId: 'flutter-and-friends-ad8fe',
    authDomain: 'flutter-and-friends-ad8fe.firebaseapp.com',
    storageBucket: 'flutter-and-friends-ad8fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMfWLMcSzqnPH9SZcjfxmEcqAYQdj28I',
    appId: '1:148076616084:android:f3c8cfe6bccb9cfa38d781',
    messagingSenderId: '148076616084',
    projectId: 'flutter-and-friends-ad8fe',
    storageBucket: 'flutter-and-friends-ad8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVFQD2DMEiNDnVKWSsZCQBEIp0cvpI_c',
    appId: '1:148076616084:ios:6b65b71342755d6c38d781',
    messagingSenderId: '148076616084',
    projectId: 'flutter-and-friends-ad8fe',
    storageBucket: 'flutter-and-friends-ad8fe.firebasestorage.app',
    iosBundleId: 'com.felangel.flutter-and-friends',
  );
}
