import 'package:flutter/foundation.dart';
import 'package:flutter_and_friends/firebase_options.dart';

export 'version.dart';

/// Public schedule feed published by the conference website alongside the
/// site itself. Served with permissive CORS and a short cache lifetime so a
/// mid-conference change reaches the app quickly.
const scheduleFeedUrl = 'https://flutterfriends.dev/schedule.json';

/// Debug-only default for the local feed host override (see
/// `SettingsCubit.debugUseLocalFeed`). See [localHost] for why this differs
/// on Android emulators.
String get defaultDebugFeedHost => 'http://$localHost:4500';

/// The audience Q&A (see `lib/qa`) stores questions and votes in Firestore
/// and identifies devices with anonymous Firebase Auth, in the same Firebase
/// project the website deploys to. The project configuration is
/// `lib/firebase_options.dart`, generated by `flutterfire configure`.
///
/// Debug builds talk to the local Firebase emulator suite instead, started
/// with `npx firebase-tools emulators:start` from the repository root, so
/// the feature works out of the box during development without touching
/// production data. Pass `--dart-define=USE_FIREBASE_EMULATORS=false` to
/// debug against the real project.
bool get useFirebaseEmulators =>
    kDebugMode &&
    const bool.fromEnvironment('USE_FIREBASE_EMULATORS', defaultValue: true);

const firebaseAuthEmulatorPort = 9099;
const firebaseFirestoreEmulatorPort = 8080;

/// Whether Firebase, and with it the Q&A, is available on this platform.
/// When false the Q&A screen explains that the feature is unavailable
/// instead of failing on every request.
bool get isQaConfigured => DefaultFirebaseOptions.isSupportedPlatform;

/// The pub quiz (see `lib/pub_quiz`) lives in the same Firestore database
/// and uses the same anonymous identity as the Q&A, so it is available on
/// exactly the same platforms.
bool get isPubQuizConfigured => DefaultFirebaseOptions.isSupportedPlatform;

/// The Firestore document under `pub_quizzes` that the conference website
/// drives; the app only ever plays this one quiz.
const pubQuizId = 'pub-quiz-2026';

/// The highscore (see `lib/highscore`) publishes how many people each
/// device has collected to the same Firestore database, under the same
/// anonymous identity as the Q&A, so it is available on exactly the same
/// platforms.
bool get isHighscoreConfigured => DefaultFirebaseOptions.isSupportedPlatform;

/// The developer machine as seen from the running app. On an Android
/// emulator `localhost` resolves to the emulator itself, not the host
/// machine; `10.0.2.2` is the documented alias back to the host loopback
/// interface. Every other target (web, iOS simulator, desktop) reaches the
/// host directly via `localhost`.
String get localHost {
  if (!kIsWeb && defaultTargetPlatform == TargetPlatform.android) {
    return '10.0.2.2';
  }
  return 'localhost';
}
